update snack case to camel case in qcv and change docker base

diff --git a/Dockerfile.local b/Dockerfile.local
--- a/Dockerfile.local
+++ b/Dockerfile.local
@@ -11,7 +11,7 @@ COPY package*.json ./
 RUN npm install --frozen-lockfile
 
 COPY . .
-RUN npx ng build --configuration=production || { echo 'Angular build failed'; exit 1; }
+RUN npx ng build --configuration=development || { echo 'Angular build failed'; exit 1; }
 
 # -------------------------
 # Step 2: Serve with Nginx
